todoist_api_token: "YOUR_TODOIST_TOKEN"
default_project: "Events"
label: "Event"

# If false, script will run only once. Else it will run every n seconds
keep_running: false
run_every: 600 # seconds

calendars:
  - "primary"

log_level: "INFO"

task_prefix: "* ğŸ—“ï¸ *"
task_suffix: "*"